webapp/location/views.py
from flask import Blueprint, request, jsonify
from webapp.database import db_session
from sqlalchemy.orm import load_only
from webapp.location.models import City


blueprint = Blueprint('location', __name__, url_prefix='/locations')


@blueprint.route('/_autocomplete_city', methods=['GET'])
def autocomplete_city():
    with db_session() as session:
        search = request.args.get('q')
        if not search:
            search = []
        city_db = session.query(City).options(load_only('name')).filter(City.name.ilike(f'%{search}%')).limit(5)
        cities_names = [city.name for city in city_db]
        return jsonify(cities_names)

webapp/meeting/views.py
from flask import Blueprint, redirect, render_template, flash, url_for, request, jsonify, session as user_session
from flask_login import current_user, login_required
from webapp.meeting.forms import MeetingForm, ButtonForm, DeleteMeetingForm
from webapp.user.forms import UserControlForm
from webapp.methods import update_meeting, add_meeting, delete_meeting, paginate
from webapp.game.models import Game
from webapp.meeting.models import MeetingUser, GameMeeting
from webapp.location.models import City
from webapp.config import GAMES_PER_PAGE
from webapp.database import db_session
from math import ceil
from datetime import date
from sqlalchemy.orm import load_only

blueprint = Blueprint('meeting', __name__, url_prefix='/meetings')


@blueprint.route('/create_meeting', methods=['POST', 'GET'])
@login_required
def create_meeting():
    """
    При GET запросе возвращает страницу для создания встречи.
    При POST запросе, в случае успешной валидации сохраняет
    новую встречу в БД.
    """
    title = 'Создание встречи'
    meeting_form = MeetingForm(request.form)
    with db_session() as session:
        meet_data = GameMeeting.owner_meetings(session, current_user.id)
        if meet_data.count() >= 10:
            flash('Ошибка создания встречи, Вы создали слишком много встреч.')
            return render_template(
                'create_meeting.html',
                page_title=title,
                form=meeting_form,
            )

        if meeting_form.validate_on_submit():
            db_game = session.query(Game).filter(Game.name == meeting_form['game_name'].data).first()
            game_id = db_game.id if db_game else None
            db_city = session.query(City).filter(City.name == meeting_form['meeting_city'].data).first()
            city_id = db_city.id if db_city else None
            new_meeting = GameMeeting(
                game_name=meeting_form['game_name'].data,
                owner_id=current_user.id,
                create_date=date.today(),
                number_of_players=meeting_form['number_of_players'].data,
                city_name=meeting_form['meeting_city'].data,
                city_id=city_id,
                meeting_place=meeting_form['meeting_place'].data,
                meeting_date_time=f"{meeting_form['date_meeting'].data} {meeting_form['time_meeting'].data}",
                description=meeting_form['description'].data,
                number_of_subs=0,
                game_id=game_id,
                deleted=False
            )

            if add_meeting(session, new_meeting):
                flash('Вы успешно создали встречу!')
                return redirect(url_for('meeting.meetings'))

            flash('Ошибка создания встречи, попробуйте повторить позже.')

    return render_template(
        'create_meeting.html',
        page_title=title,
        form=meeting_form,
    )


@blueprint.route('/edit_meeting', methods=['GET', 'POST'])
@login_required
def edit_meeting():
    title = f'Встреча {current_user.username}'
    buttons = ButtonForm()
    confirm_form = UserControlForm()
    delete_form = DeleteMeetingForm()

    if buttons.validate_on_submit:
        user_session['current_meet'] = (
            buttons.current_meet.data if buttons.current_meet.data
            else user_session['current_meet']
        )

    meeting_form = MeetingForm()
    with db_session() as session:
        meeting_data = GameMeeting.join_meetings(session, user_session['current_meet'])
        meet_time = meeting_data.meeting_date_time.strftime("%H:%M")
        meet_date = meeting_data.meeting_date_time.strftime("%Y-%m-%d")

    return render_template(
        'edit_meeting.html',
        page_title=title,
        form=meeting_form,
        meeting_data=meeting_data,
        meet_time=meet_time,
        meet_date=meet_date,
        confirm_form=confirm_form,
        delete_form=delete_form
    )


@blueprint.route('/user_control', methods=['GET', 'POST'])
@login_required
def user_control():
    meeting_id = int(request.form['current_meet'])
    with db_session() as session:
        meeting = MeetingUser.get_meet(session, meeting_id)
        meeting.un_confirm_user() if meeting.confirmed else meeting.confirm_user()
        session.commit()

    return redirect(url_for('meeting.edit_meeting'))


@blueprint.route('/submit_edit_meet', methods=['POST'])
@login_required
def submit_edit_meet():
    meeting_form = MeetingForm()
    if meeting_form.validate_on_submit:
        with db_session() as session:
            update_meeting(session, meeting_form, user_session['current_meet'])

    return redirect(url_for('user.profile'))


@blueprint.route('/submit_delete_meet', methods=['POST'])
@login_required
def submit_delete_meet():
    delete_form = DeleteMeetingForm()
    if delete_form.validate_on_submit:
        with db_session() as session:
            delete_meeting(session, delete_form.current_meet.data)
            return redirect(url_for('user.profile'))


@blueprint.route('/', methods=['POST', 'GET'])
@login_required
def meetings():
    title = 'LFG'
    buttons = ButtonForm()
    page = int(request.args.get('p', 1))
    with db_session() as session:
        if buttons.validate_on_submit():
            meet_data = GameMeeting.sub_to_meetings(session, current_user.id)
            if meet_data.count() >= 10:
                flash('Ошибка подписки. Вы подписаны на максимальное количество встреч')
                return redirect(url_for('meeting.meetings'))
            if buttons.submit_add_wish.data:
                meet = session.query(GameMeeting).filter(GameMeeting.id == buttons.current_meet.data).first()
                new_player = MeetingUser(
                    user_id=current_user.id,
                    meeting_id=meet.id,
                    confirmed=False,
                )
                if session.query(GameMeeting).filter(
                    MeetingUser.meeting_id == meet.id
                ).filter(
                    MeetingUser.user_id == current_user.id
                ).all():
                    pass  # СЮДА НАДО ДОБАВИТЬ ПОВЕДЕНИЕ
                else:
                    session.add(new_player)
                    session.commit()

                return redirect(url_for('meeting.meetings'))

        if buttons.submit_del.data:
            player = session.query(MeetingUser).join(GameMeeting).filter(
                GameMeeting.id == buttons.current_meet.data
            ).filter(
                MeetingUser.meeting_id == GameMeeting.id
            ).filter(MeetingUser.user_id == current_user.id).one()
            session.delete(player)
            session.commit()

            return redirect(url_for('meeting.meetings'))

        if buttons.submit_edit.data:
            return redirect(url_for('user.profile'))

        active_games = GameMeeting.active_games(session).order_by(
            GameMeeting.meeting_date_time.asc()).filter(GameMeeting.number_of_players > GameMeeting.number_of_subs)
        meets_list = paginate(active_games, page, GAMES_PER_PAGE).all()
        last_page = ceil(active_games.count() / GAMES_PER_PAGE)
        current_user_meetings = GameMeeting.sub_to_meetings(session, current_user.id)
        return render_template(
            'meetings.html',
            meets_list=meets_list,
            page_title=title,
            current_page=page,
            last_page=last_page,
            buttons=buttons,
            current_user=current_user,
            current_user_meetings=current_user_meetings
        )


@blueprint.route('/_game_info', methods=['GET'])
def game_info():
    search = request.form.get('game')
    with db_session() as session:
        return jsonify(session.query(Game).filter(Game.name.ilike(f'%{search}%')).first())


@blueprint.route('/_autocomplete', methods=['GET'])
def autocomplete():
    with db_session() as session:
        search = request.args.get('q')
        if not search:
            search = []
        games_db = session.query(Game).options(load_only('name')).filter(Game.name.ilike(f'%{search}%')).limit(15)
        games_names = [game.name for game in games_db]
        return jsonify(games_names)

webapp/news/views.py
from flask import Blueprint, render_template, request
from webapp.methods import get_news

blueprint = Blueprint('news', __name__, url_prefix='/news')


@blueprint.route('/news', methods=['GET'])
@blueprint.route('/news/<int:id>', methods=['GET'])
def news():
    news_id = request.args['id']
    news_data = list(filter(lambda n: n['id'] == news_id, get_news()))[0]
    if news_data['title']:
        title = news_data['title']
    else:
        title = 'Новости'
    return render_template('news.html', news_data=news_data, page_title=title)

webapp/user/views.py
from werkzeug.security import generate_password_hash
from flask import Blueprint, current_app, redirect, render_template, flash, url_for
from flask_login import current_user, login_user, logout_user, login_required
from webapp.user.forms import LoginForm, RegistrationForm, ProfileForm, AvatarForm
from webapp.meeting.forms import ButtonForm
from webapp.methods import update_profile
from webapp.user.models import User, UserProfile
from webapp.meeting.models import MeetingUser, GameMeeting
from webapp.database import db_session
import os
import sqlalchemy.exc

blueprint = Blueprint('user', __name__, url_prefix='/user')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Успешный вход')
            return redirect(url_for('index'))

        flash('Неправильное имя пользователя или пароль')
        return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@blueprint.route('/registration', methods=['POST', 'GET'])
def registration():
    """
    При GET запросе возвращает страницу для регистрации.
    При POST запросе, в случае успешной валидации сохраняет
    нового пользователя в БД.
    """
    title = 'Регистрация'
    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():
        hash_pass = generate_password_hash(
            registration_form['password'].data
        )
        with db_session() as session:
            new_user = User(
                username=registration_form['username'].data,
                password=hash_pass,
                email=registration_form['email'].data,
                role='1'
            )
            try:
                session.add(new_user)
                session.commit()
                flash('Вы успешно зарегистрировались!')
                return redirect(url_for('user.login'))
            except sqlalchemy.exc:  # sqlalchemy.exc не обрабатываются, нужно понять как обрабатывать
                flash('Ошибка регистрации, попробуйте повторить позже.')

    return render_template(
        'registration.html',
        page_title=title,
        form=registration_form
    )


@blueprint.route('/profile', methods=['POST', 'GET'])
@login_required
def profile():
    title = f'Профиль {current_user.username}'

    buttons = ButtonForm()
    avatar_form = AvatarForm()
    img_dict = os.listdir(os.path.join(current_app.static_folder, "images/avatars"))
    avatar_form.choose_avatar.choices = [(f'images/avatars/{img}', img) for img in img_dict]
    with db_session() as session:
        if buttons.validate_on_submit():
            player = session.query(MeetingUser).join(GameMeeting).filter(
                GameMeeting.id == buttons.current_meet.data
            ).filter(
                MeetingUser.meeting_id == GameMeeting.id
            ).filter(MeetingUser.user_id == current_user.id).one()
            session.delete(player)
            session.commit()
            return redirect(url_for('user.profile'))
        if not UserProfile.join_profile(session, current_user.id):
            new_profile = UserProfile(
                owner_id=current_user.id,
                name='',
                surname='',
                country='',
                city='',
                favorite_games='',
                desired_games='',
                about_user=''
            )
            session.add(new_profile)
            session.commit()
        profile_data = UserProfile.join_profile(session, current_user.id)
        meets_data = GameMeeting.owner_meetings(session, current_user.id).order_by(GameMeeting.meeting_date_time.asc())
        meets_user = GameMeeting.sub_to_meetings(session, current_user.id).order_by(GameMeeting.meeting_date_time.asc())
        return render_template(
            'profile.html',
            page_title=title,
            profile_data=profile_data,
            meets_data=meets_data,
            meets_user=meets_user,
            buttons=buttons,
            img_dict=img_dict,
            avatar_form=avatar_form
        )


@blueprint.route('/change_avatar', methods=['POST', 'GET'])
@login_required
def change_avatar():
    avatar_form = AvatarForm()
    with db_session() as session:
        profile = session.query(UserProfile).filter(UserProfile.owner_id == current_user.id).first()
        profile.avatar = avatar_form['choose_avatar'].data
        session.commit()
    flash('Личные данные успешно сохранены!')
    return redirect(url_for('user.profile'))


@blueprint.route('/edit_profile')
@login_required
def edit_profile():
    title = f'Профиль {current_user.username}'
    with db_session() as session:
        profile_data = UserProfile.join_profile(session, current_user.id)
    profile_form = ProfileForm()
    return render_template(
        'edit_profile.html',
        page_title=title,
        form=profile_form,
        profile_data=profile_data
    )


@blueprint.route('/submit_profile', methods=['POST', 'GET'])
def submit_profile():
    form = ProfileForm()
    with db_session() as session:
        if bool(UserProfile.query.filter_by(owner_id=current_user.id).first()):
            update_profile(session, form, current_user)
            flash('Личные данные успешно сохранены!')
            return redirect(url_for('user.profile'))
        new_profile = UserProfile(
            owner_id=current_user.id,
            name=form['name'].data,
            surname=form['surname'].data,
            country=form['country'].data,
            city=form['city'].data,
            favorite_games=form['favorite_games'].data,
            desired_games=form['desired_games'].data,
            about_user=form['about_user'].data
        )

        session.add(new_profile)
        session.commit()

    flash('Личные данные успешно сохранены!')
    return redirect(url_for('user.profile'))

webapp/templates/create_meeting.html
{% extends 'base.html' %}

{% block content %}

<section class="content container">
    <div class="row">
      <div class="col-5">

        <form action="" method="post" class="py-3">
            {{ form.hidden_tag() }}
            <div class="form-group">

              {{ form.game_name.label() }}:{{ form.game_name() }}
              <script>
                $(function() {
                  $("#game_autocomplete").autocomplete({
                    source:function(request, response) {
                      $.getJSON("{{url_for('meeting.autocomplete')}}",{
                        q: request.term,
                      }, function(data) {
                        response(data);
                      }); 
                    },
                    minLength: 2,
                    select: function(event, ui) {
                      console.log(ui.item.value);
                    }
                  });
                })
              </script>

              {{ form.meeting_city.label() }}:{{ form.meeting_city() }}
              <script>
                $(function() {
                  $("#city_autocomplete").autocomplete({
                    source:function(request, response) {
                      $.getJSON("{{url_for('location.autocomplete_city')}}",{
                        q: request.term,
                      }, function(data) {
                        response(data);
                      }); 
                    },
                    minLength: 2,
                    select: function(event, ui) {
                      console.log(ui.item.value);
                    }
                  });
                })
              </script>
          {% for field in form if field.name not in ['csrf_token', 'submit', 'game_name', 'meeting_city'] %}
            <div class="form-group">
              {{ field.label() }}
              {{ field() }}
              
                <p class="error text-dark text-center">
                  {% for e in field.errors %}
                    {{ e }}
                  {% endfor %}
                </p>
                
            </div>
            {% endfor %}

          {{ form.submit() }}

        </form>
      
      </div>  
    </div>
</section>
{% endblock content %}   

webapp/templates/edit_meeting.html
{% extends 'base.html' %}

{% block content %}

<section class="content container">
    <div class="row">
      <div class="col-4 border-right">

        <form action="{{url_for('meeting.submit_edit_meet')}}" method="post" class="py-1">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h4 class="text-left">{{ meeting_data.game_name }}</h4>
            </div>
            <div class="row mt-2">
              <div class="col"><label class="labels">{{ form.game_name.label }}{{ form.game_name(value=meeting_data.game_name) }}</div>
            </div>
            <script>
              $(function() {
                $("#game_autocomplete").autocomplete({
                  source:function(request, response) {
                    $.getJSON("{{url_for('meeting.autocomplete')}}",{
                      q: request.term,
                    }, function(data) {
                      response(data);
                    }); 
                  },
                  minLength: 2,
                  select: function(event, ui) {
                    console.log(ui.item.value);
                  }
                });
              })
            </script>

            <div class="row mt-2">
              <div class="col"><label class="labels">{{ form.meeting_city.label }}{{ form.meeting_city(value=meeting_data.city_name) }}</div>
            </div>
            <script>
              $(function() {
                $("#city_autocomplete").autocomplete({
                  source:function(request, response) {
                    $.getJSON("{{url_for('location.autocomplete_city')}}",{
                      q: request.term,
                    }, function(data) {
                      response(data);
                    }); 
                  },
                  minLength: 2,
                  select: function(event, ui) {
                    console.log(ui.item.value);
                  }
                });
              })
            </script>
            
            <div class="row mt-1">
              <div class="col"><label class="labels text-left">{{ form.number_of_players.label }}{{ form.number_of_players(value=meeting_data.number_of_players) }}</div>
            </div>
           <div class="row mt-1">
              <div class="col"><label class="labels text-left">{{ form.meeting_place.label }}{{ form.meeting_place(value=meeting_data.meeting_place) }}</div>
            </div>
            <div class="row mt-1">  
              <div class="col"><label class="labels text-left">{{ form.date_meeting.label }}{{ form.date_meeting(value=meet_date) }}</div>
            </div>
            <div class="row mt-1">
              <div class="col"><label class="labels text-left">{{ form.time_meeting.label }}{{ form.time_meeting(value=meet_time) }}</div>
            </div>
            <div class="row mt-1">
              <div class="col"><label class="labels text-left">{{ form.description.label }}{{ form.description(value=meeting_data.description) }}</div>
              <script> var textarea = document.getElementById('meet_description'); textarea.innerHTML = "{{ meeting_data.description }}" </script>
          </div>
            <div class="mt-3 text-left"> {{ form.submit() }}</div>
        </form>
        <form action="{{url_for('meeting.submit_delete_meet')}}" method="post" class="py-3">
          {{ form.hidden_tag() }}
          {{ delete_form.current_meet(value=meeting_data.id, hidden=True) }}
          <div class="form-group">
            <button type="delete" class="btn btn-danger">Удалить встречу</button>
          </div> 
        </form>
      </div> 

      <div class="col-md-4 mt-3 border-right">
        <h4 class="text-left mb-3">Список подписанных</h4>
        {% for user in meeting_data.users %}
          {% if not user.confirmed %}
                  <div class="row align-items-center">
                    <div class="col-6 mt-3 d-flex justify-content-start">
                    <a href="#" data-toggle="modal" data-target="#ProfileModal{{user.user.username}}" class="link-primary"><h6 class="card-subtitle mb-2 text-primary">
                    {{ user.user.username }}</h6></a>
                    </div>
                    <div class="col-6 mt-3 d-flex justify-content-end">
                      <form action="{{url_for('meeting.user_control')}}" method="post" class="py-3">
                        {{ form.hidden_tag() }}
                        {{ confirm_form.current_meet(value=user.id, hidden=True) }}
                        <div class="form-group">
                          <button type="submit" class="btn btn-warning">Подтвердить</button>
                        </div>                       
                      </form>
                    </div>
                  </div>  
                <!-- Modal -->
                <div class="modal fade" id="ProfileModal{{user.user.username}}" tabindex="-1" role="dialog" aria-labelledby="ProfileModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="ProfileModalLabel">Профиль {{ user.user.user_profile.name }}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                            <div class="row mt-2">
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.name }}</div>
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.surname }}</div>
                            </div>
                            <div class="row mt-3">
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.country }}</div>
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.city }}</div>
                            </div>
                            <div class="row mt-3">
                              <div class="col-md-12"><label class="labels">{{ user.user.email }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.favorite_games }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.desired_games }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.about_user }}</div>
                            </div>
                        </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                          </div>
                      </div>
                      
                  </div>
                </div>

          {% endif %}
        {% endfor %}
      </div>

      <div class="col-md-4 mt-3 border-right">
        <h4 class="text-left mb-3">Список подтвержденных</h4>
        {% for user in meeting_data.users %}
          {% if user.confirmed %}
                <div class="row align-items-center">
                  <div class="col-6 mt-3 d-flex justify-content-start">
                  <a href="#" data-toggle="modal" data-target="#ProfileModal{{user.user.username}}" class="link-primary"><h6 class="card-subtitle mb-2 text-primary">
                  {{ user.user.username }}</h6></a>
                  </div>
                  <div class="col-6 mt-3 d-flex justify-content-end">
                    <form action="{{url_for('meeting.user_control')}}" method="post" class="py-3">
                      {{ form.hidden_tag() }}
                      {{ confirm_form.current_meet(value=user.id, hidden=True) }}
                      <div class="form-group">
                        <button type="submit" class="btn btn-warning">Отменить</button>
                      </div>                       
                    </form>
                  </div>
                </div> 
                <!-- Modal -->
                <div class="modal fade" id="ProfileModal{{user.user.username}}" tabindex="-1" role="dialog" aria-labelledby="ProfileModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="ProfileModalLabel">Профиль {{ user.user.user_profile.name }}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                            <div class="row mt-2">
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.name }}</div>
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.surname }}</div>
                            </div>
                            <div class="row mt-3">
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.country }}</div>
                              <div class="col-md-6"><label class="labels">{{ user.user.user_profile.city }}</div>
                            </div>
                            <div class="row mt-3">
                              <div class="col-md-12"><label class="labels">{{ user.user.email }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.favorite_games }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.desired_games }}</div>
                              <div class="col-md-12"><label class="labels">{{ user.user.user_profile.about_user }}</div>
                            </div>
                        </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                          </div>
                      </div>
                      
                  </div>
                </div>
                
          {% endif %}
        {% endfor %}
      </div>

    </div>
</section> 
{% endblock content %}   

webapp/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}


    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if current_user.user_profile.avatar %}
                <img class="rounded-circle mt-5" width="150px" src={{url_for('static', filename=current_user.user_profile.avatar) }}>
                {% endif %}
                <span class="font-weight-bold">{{ current_user.username }}</span><span class="text-black-50">{{ current_user.email }}</span><span> </span></div>
        </div>
        <div class="col-md-5 border-right">
            <form action="{{ url_for('user.submit_profile') }}" method="post" class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">{{ form.name.label }}{{ form.name(value=profile_data.name) }}</div>
                    <div class="col-md-6"><label class="labels">{{ form.surname.label }}{{ form.surname(value=profile_data.surname) }}</div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><label class="labels">{{ form.country.label }}{{ form.country(value=profile_data.country) }}</div>
                    <div class="col-md-6"><label class="labels">{{ form.city.label }}{{ form.city(value=profile_data.city) }}</div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">{{ form.email.label }}{{ form.email(value=current_user.email) }}</div>
                    <div class="col-md-12"><label class="labels">{{ form.favorite_games.label }}{{ form.favorite_games(value=profile_data.favorite_games) }}</div>
                    <div class="col-md-12"><label class="labels">{{ form.desired_games.label }}{{ form.desired_games(value=profile_data.desired_games) }}</div>
                    <div class="col-md-12"><label class="labels">{{ form.about_user.label }}{{ form.about_user(value=profile_data.about_user) }}</div>
                </div>
                <div class="mt-5 text-left"> {{ form.submit() }}</div>
            </form>
        </div>
        
    </div>
</div>
{% endblock content %}   

webapp/templates/news.html
{% extends 'base.html' %}

{% block content %}

<section class="content container">
    <div class="row">
        <div class="col-10">
            <img src={{ news_data.image }}>
            <h3>{{ news_data.title }}</h3>
            <h6>by: {{ news_data.author }}</h6>
            <h6>{{ news_data.published }}</h6>
            <h5>{{ news_data.content }}</h5>
        </div>
    </div>

</section>

{% endblock content %}